-- This section of code, building on the icustays30 table generated by the icustays_data code, adds sepsis diagnosis, heart failure diagnosis, and central venous pressure monitoring information

-- Keep only the variables needed from icustays30
DROP TABLE IF EXISTS public.stay0;
CREATE TABLE public.stay0 AS
SELECT subject_id, hadm_id, stay_id, intime, outtime, los, survival_status, survival_day, thirty_day_death, one_year_death, hospital_expire_flag, 
    CASE 
        WHEN survival_status = 1 AND survival_day <= 30 THEN 1
        ELSE 0
    END AS surv30_status,
    LEAST(survival_day, 30) AS surv30_day,
    CASE 
        WHEN survival_status = 1 AND survival_day <= 365 THEN 1
        ELSE 0
    END AS surv365_status,
    LEAST(survival_day, 365) AS surv365_day,
gender, age, insurance, 
renal_disease, severe_liver_disease, metastatic_cancer, aids,
mbp_first AS mbp, heart_rate_first AS heart_rate, spo2_first AS spo2, 
pao2fio2ratio_first AS pao2fio2ratio, lactate_first AS lactate, creatinine_first AS creatinine, bun_first AS bun, potassium_first AS potassium, platelet_first AS platelet, inr_first AS inr, alt_first AS alt, bilirubin_total_first AS bilirubin, ntprobnp, 
sofa, apsiii,
vasoactive, mechanical_ventilation, lvef
FROM public.icustays30;

-- Find the icd_code and icd_version for heart failure and store them in the hf_icd table
DROP TABLE IF EXISTS public.hf_icd;
CREATE TABLE public.hf_icd AS
SELECT * FROM mimiciv_hosp.d_icd_diagnoses
WHERE LOWER(long_title) LIKE '%heart failure%'
    AND LOWER(long_title) NOT LIKE '%without heart failure%'
    AND LOWER(long_title) NOT LIKE '%postprocedural%';
    
-- Find hadm_ids of admissions that contain a heart failure diagnosis listed in the hf_icd table, from the diagnoses_icd table
DROP TABLE IF EXISTS public.hf_hadm;
CREATE TABLE public.hf_hadm AS
SELECT DISTINCT d.hadm_id
FROM mimiciv_hosp.diagnoses_icd AS d
INNER JOIN public.hf_icd AS h
ON d.icd_code = h.icd_code AND d.icd_version = h.icd_version;
-- Among the 546028 admissions, a total of 80858 hadm_ids had a heart failure diagnosis
SELECT COUNT(*) FROM mimiciv_hosp.admissions;
SELECT COUNT(*) FROM public.hf_hadm;

-- Add heart failure diagnosis status (binary)
DROP TABLE IF EXISTS public.stay1;
CREATE TABLE public.stay1 AS
SELECT ie.*,
    CASE 
        WHEN hf.hadm_id IS NOT NULL THEN 1
        ELSE 0
    END AS heart_failure
FROM public.stay0 AS ie
LEFT JOIN public.hf_hadm AS hf
ON ie.hadm_id = hf.hadm_id;
SELECT COUNT(*) FROM public.stay1; --74824
SELECT SUM(heart_failure) FROM public.stay1; --21616
-- Of the 74824 ICU records, a total of 21616 records had a heart failure diagnosis.

-- Add sepsis diagnosis status (binary) and the time of diagnosis
DROP TABLE IF EXISTS public.stay2;
CREATE TABLE public.stay2 AS
SELECT ie.*,
    CASE WHEN se.sepsis3 IS NOT NULL THEN 1 ELSE 0 END AS sepsis,
    sofa_time AS sepsis_time
FROM public.stay1 AS ie
LEFT JOIN mimiciv_derived.sepsis3 AS se
ON ie.stay_id = se.stay_id;
SELECT SUM(sepsis) FROM public.stay2; --37142

-- Add disease grouping
DROP TABLE IF EXISTS public.stay3;
CREATE TABLE public.stay3 AS
SELECT *,
    CASE 
        WHEN heart_failure=0 AND sepsis=1 THEN 'sepsis'
        WHEN heart_failure=1 AND sepsis=0 THEN 'HF'
        WHEN heart_failure=1 AND sepsis=1 THEN 'HFsepsis'
        ELSE NULL
    END AS disease_group
FROM public.stay2;
SELECT COUNT(disease_group) FROM public.stay3; --46627
SELECT COUNT(*) FROM public.stay3
WHERE disease_group='HFsepsis'; --12131

------------------------------------------------------------------------------------------

-- This section adds central venous pressure monitoring information to icustays. The following is the exploration process, which is commented out and not executed after exploration is complete.
-- -- Find the itemid for central venous pressure
-- SELECT * FROM mimiciv_icu.d_items
-- WHERE LOWER(label) LIKE '%central venous pressure%'
-- OR LOWER(label) LIKE '%cvp%'; --220074
-- -- Query CVP monitoring records in the chartevents table
-- SELECT * FROM mimiciv_icu.chartevents
-- WHERE itemid = 220074; -- 993375 records in total
-- SELECT DISTINCT valueuom FROM mimiciv_icu.chartevents
-- WHERE itemid = 220074; -- Only mmHg as the unit


-- Extract CVP monitoring information, including whether CVP monitoring was performed, the time of the first CVP measurement, and the value of the first CVP measurement.
-- Note that when determining the first CVP measurement, in addition to requiring that the CVP measurement time is the earliest among all CVP records for that stay_id, the CVP measurement time must also be after intime. After keeping only the first ICU stay_id under each admission hadm_id, I further explored the CVP records for each stay_id, including the measured value valuenum and measurement time charttime. I found that a small number of stay_ids (129 records) had their first CVP measurement earlier than intime, and all their charttimes were after intime-24h. For these 129 stay_ids, if the CVP records before intime are not considered and only those after intime are considered, then 123 stay_ids had CVP monitoring after intime, all of which were monitored within intime+12h, with 120 of them monitored within intime+6h. This indicates that, if CVP records before intime are ignored and only those after intime are considered, it barely affects the determination of whether this stay_id had early CVP monitoring. However, there are 129-123=6 stay_ids that had CVP records before intime but none after intime. If the start time for the first CVP measurement is extended to intime-6h, as the MIMIC official code repository does for many laboratory results, then only 7 stay_ids had their first CVP time between intime-24h and intime-6h, and all 7 records underwent early CVP monitoring (6 within 6h, 1 within 12h).
DROP TABLE IF EXISTS public.stay4;
CREATE TABLE public.stay4 AS
WITH cvp_filtered AS (
    -- Filter CVP measurement records from chartevents whose charttime falls between intime and outtime in icustays
    SELECT 
        ce.stay_id,
        ce.charttime AS cvp_time,
        ce.valuenum AS cvp,
        ie.intime
    FROM mimiciv_icu.chartevents AS ce
    LEFT JOIN mimiciv_icu.icustays AS ie 
        ON ce.stay_id = ie.stay_id
    WHERE ce.itemid = 220074
      AND ce.charttime BETWEEN ie.intime AND ie.outtime
),
cvp_ranked AS (
    -- Partition the above CVP monitoring records by stay_id, order by charttime, and mark the first record
    SELECT 
        stay_id,
        cvp_time,
        cvp,
        ROW_NUMBER() OVER (PARTITION BY stay_id ORDER BY cvp_time) AS cvp_order
    FROM cvp_filtered
)
-- Join back to stay3 to add the new fields
SELECT 
    ie.*,    
    EXTRACT(EPOCH FROM (cv.cvp_time - ie.intime))/3600 AS first_cvp_interval,
    cv.cvp AS first_cvp
FROM public.stay3 AS ie
LEFT JOIN cvp_ranked AS cv 
    ON ie.stay_id = cv.stay_id
    AND cv.cvp_order = 1;  -- Keep only the first record (the first after sorting)

SELECT COUNT(*) FROM public.stay4; --74824
SELECT COUNT(first_cvp) FROM public.stay4; --19731
