-- The icustays16 table generated by the following code contains all ICU records with los of at least 1 day, 74824 records in total.
-- This section does not filter patients' diagnoses or disease information, nor does it select the first ICU record for the same patient, to improve generalizability.

-- This block removes duplicate ICU records: when the same subject_id has multiple repeated ICU admissions, only the first is kept and the rest are removed. This section has been commented out to improve generalizability. This is because the multiple admissions of the same patient have different diagnosis lists; if only the first ICU record were kept, that record might lack the specified diagnosis and thus exclude the patient entirely, even though a later ICU record for the same patient might contain the target diagnosis.
-- DROP TABLE IF EXISTS public.icustays3;
-- CREATE TABLE public.icustays3 AS
-- WITH icutemp AS
-- (SELECT *,
--  ROW_NUMBER() OVER (PARTITION BY subject_id ORDER BY intime) AS stay_order
--  FROM public.icustays2)
-- SELECT subject_id, hadm_id, stay_id, intime, outtime, los
--     FROM icutemp
--     WHERE stay_order = 1;
-- SELECT COUNT(*) FROM public.icustays3;

-- The icustays table contains a total of 94458 ICU admission records
SELECT COUNT(*) FROM mimiciv_icu.icustays; --94458
-- Remove records with los less than 1 day, resulting in 74829 ICU admission records
DROP TABLE IF EXISTS public.icustays2;
CREATE TABLE public.icustays2 AS
SELECT subject_id, hadm_id, stay_id, intime, outtime, los
FROM mimiciv_icu.icustays
WHERE los >= 1;
SELECT COUNT(*) FROM public.icustays2; --74829

-- Add survival data.
-- Add the discharge time of the last admission to the patients table, generating the patients2 table.
DROP TABLE IF EXISTS public.patients2;
CREATE TABLE public.patients2 AS
SELECT 
    pa.*, 
    MAX(ad.dischtime) AS last_dischtime    
FROM mimiciv_hosp.patients AS pa
LEFT JOIN mimiciv_hosp.admissions AS ad
ON pa.subject_id = ad.subject_id
GROUP BY pa.subject_id;
SELECT COUNT(*) FROM mimiciv_hosp.patients; --364627
SELECT COUNT(last_dischtime) FROM public.patients2; --223452. Not all patients have admission records.
-- Extract the time of death from the dod variable in the patients table. Note that deathtime from the admissions table should not be used as the time of death, because it refers to death during the hospitalization.
-- Determine the follow-up cutoff time. If dod is not null, the patient ultimately died; the follow-up cutoff time is dod and the status is 1 (dead). If dod is null, the status is 0 (survived), and the follow-up cutoff time is the discharge time of the patient's last admission plus 1 year.
-- The MIMIC database only has the date of death, not an exact time point. Based on later experience, the time of death is set to 23:59:59 on the day of dod, to avoid as much as possible the situation where the time of death precedes the admission time.
-- Add survival status and survival time
DROP TABLE IF EXISTS public.icustays3;
CREATE TABLE public.icustays3 AS
SELECT ie.*, 
    (DATE_TRUNC('day', pa.dod) + INTERVAL '23 hours 59 minutes 59 seconds')::TIMESTAMP AS tod,
    CASE
        WHEN pa.dod IS NOT NULL THEN 1
        ELSE 0
    END AS survival_status,
    CASE
        WHEN pa.dod IS NOT NULL THEN (DATE_TRUNC('day', pa.dod) + INTERVAL '23 hours 59 minutes 59 seconds')::TIMESTAMP
        ELSE pa.last_dischtime + INTERVAL '1 year'
    END AS survival_time
FROM public.icustays2 AS ie
LEFT JOIN public.patients2 AS pa
ON ie.subject_id = pa.subject_id;
SELECT COUNT(survival_time) FROM public.icustays3; --74829

-- Calculate prognostic indicators such as survival days, 30-day death, and 1-year death. Use the interval between the time of death and intime to determine whether death occurred within 30 days or 1 year after ICU admission.
DROP TABLE IF EXISTS public.icustays4;
CREATE TABLE public.icustays4 AS
SELECT *,
    EXTRACT(EPOCH FROM (survival_time - intime)) / 86400 AS survival_day,
    CASE 
        WHEN tod IS NULL THEN 0
        WHEN tod > intime + INTERVAL '30 DAY' THEN 0
        WHEN tod <= intime + INTERVAL '30 DAY' 
            AND tod > intime THEN 1
        ELSE 0
    END AS thirty_day_death,
    CASE
        WHEN tod IS NULL THEN 0
        WHEN tod > intime + INTERVAL '1 YEAR' THEN 0
        WHEN tod <= intime + INTERVAL '1 YEAR' 
            AND tod > intime THEN 1
        ELSE 0
    END AS one_year_death
FROM public.icustays3;
-- Found 5 records with negative survival_day
SELECT * FROM public.icustays4
WHERE survival_day < 0;
-- After removing records with negative survival_day, 74824 records remain
DELETE FROM public.icustays4 
WHERE survival_day < 0;
SELECT COUNT(*) FROM public.icustays4;

-- Add hospital_expire_flag, insurance, race
-- Querying shows that MIMIC has 33 different types of race; following the NHANES approach, they are merged into 6 different categories: Mexican American, Other Hispanic, Non-Hispanic White, Non-Hispanic Black, Non-Hispanic Asian, Other Race - Including Multi-Racial
DROP TABLE IF EXISTS public.icustays5;
CREATE TABLE public.icustays5 AS
SELECT ie.*, ad.hospital_expire_flag, ad.insurance,
    CASE 
        WHEN ad.race IN ('PATIENT DECLINED TO ANSWER', 'UNABLE TO OBTAIN', 'UNKNOWN') 
             THEN 'Unknown or Not Reported'
        WHEN ad.race LIKE 'HISPANIC%' OR ad.race = 'SOUTH AMERICAN' THEN 'Hispanic'
        WHEN ad.race LIKE 'WHITE%' OR ad.race = 'PORTUGUESE' THEN 'Non-Hispanic White'
        WHEN ad.race IN ('BLACK/AFRICAN', 'BLACK/AFRICAN AMERICAN', 'BLACK/CAPE VERDEAN', 'BLACK/CARIBBEAN ISLAND') 
             THEN 'Non-Hispanic Black'
        WHEN ad.race LIKE 'ASIAN%' THEN 'Non-Hispanic Asian'
        ELSE 'Other Race - Including Multi-Racial'
    END AS race
FROM public.icustays4 AS ie
LEFT JOIN mimiciv_hosp.admissions AS ad
ON ie.hadm_id = ad.hadm_id;

-- Add age, gender
DROP TABLE IF EXISTS public.icustays6;
CREATE TABLE public.icustays6 AS
SELECT ie.*,
    pa.anchor_age + EXTRACT(EPOCH FROM ie.intime - MAKE_TIMESTAMP(pa.anchor_year, 1, 1, 0, 0, 0)) / 31556908.8 AS age,
    pa.gender
FROM public.icustays5 AS ie
LEFT JOIN mimiciv_hosp.patients AS pa
ON ie.subject_id = pa.subject_id;

-- Look up weight and BMI
-- Note: in the official code, first_day_height and first_day_weight take the average of multiple measurements within the time window, but first_day_lab later takes the maximum and minimum values
-- Obtain height from the first_day_height table
DROP TABLE IF EXISTS public.icustays7;
CREATE TABLE public.icustays7 AS
SELECT ie.*, he.height
FROM public.icustays6 AS ie
LEFT JOIN mimiciv_derived.first_day_height AS he
ON ie.stay_id = he.stay_id;
SELECT COUNT(height) FROM public.icustays7; -- 36455 height records

-- Obtain weight data from the first_day_weight table and calculate BMI
DROP TABLE IF EXISTS public.icustays8;
CREATE TABLE public.icustays8 AS
SELECT ie.*, we.weight, we.weight/(ie.height^2)*10000 AS BMI
FROM public.icustays7 AS ie
LEFT JOIN mimiciv_derived.first_day_weight AS we
ON ie.stay_id = we.stay_id;
SELECT COUNT(weight) FROM public.icustays8; -- 72922 weight records
SELECT COUNT(BMI) FROM public.icustays8; -- 36395 BMI records

-- Add the Charlson comorbidity index and several medical history items
DROP TABLE IF EXISTS public.icustays9;
CREATE TABLE public.icustays9 AS
SELECT 
    ie.*, cs.charlson_comorbidity_index, 
    cs.renal_disease,
    cs.severe_liver_disease, 
    cs.metastatic_solid_tumor AS metastatic_cancer, 
    cs.aids
FROM public.icustays8 AS ie
LEFT JOIN mimiciv_derived.charlson AS cs
ON ie.hadm_id = cs.hadm_id;

-- Add the APSIII score
DROP TABLE IF EXISTS public.icustays10;
CREATE TABLE public.icustays10 AS
SELECT ie.*, aps.apsiii
FROM public.icustays9 AS ie
LEFT JOIN mimiciv_derived.apsiii AS aps
ON ie.stay_id = aps.stay_id;

-- Obtain the gcs_min score from first_day_gcs
DROP TABLE IF EXISTS public.icustays11;
CREATE TABLE public.icustays11 AS
SELECT ie.*, gcs.gcs_min
FROM public.icustays10 AS ie
LEFT JOIN mimiciv_derived.first_day_gcs AS gcs
ON ie.stay_id = gcs.stay_id;

-- Add the first non-null gcs value within the ICU first-day time window
DROP TABLE IF EXISTS public.icustays12;
CREATE TABLE public.icustays12 AS
-- First CTE: filter non-null gcs records within the time window (basic filtering)
WITH temp1 AS (
    SELECT 
        gc.stay_id,
        gc.gcs,
        gc.charttime,
        ie.intime
    FROM mimiciv_derived.gcs AS gc
    INNER JOIN mimiciv_icu.icustays AS ie 
        ON gc.stay_id = ie.stay_id
    WHERE 
        gc.gcs IS NOT NULL
        AND gc.charttime BETWEEN (ie.intime - INTERVAL '6 HOUR') 
                             AND (ie.intime + INTERVAL '1 DAY')
),
-- Second CTE: based on temp1, take the first gcs record for each stay_id (in ascending time order)
temp2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        gcs
    FROM temp1
    ORDER BY stay_id, charttime ASC  -- group first, then take the first record by time
)
-- Main query: create the new table, left join to retain all records of the original table
SELECT 
    ie.*,
    temp2.gcs AS gcs_first  -- automatically NULL when there is no matching record
FROM public.icustays11 AS ie
LEFT JOIN temp2 
    ON ie.stay_id = temp2.stay_id;
-- In fact, temp1 and temp2 above can be merged

-- Add the LODS score
DROP TABLE IF EXISTS public.icustays13;
CREATE TABLE public.icustays13 AS
SELECT ie.*, lo.lods
FROM public.icustays12 AS ie
LEFT JOIN mimiciv_derived.lods AS lo
ON ie.stay_id = lo.stay_id;

-- Add the OASIS score
DROP TABLE IF EXISTS public.icustays14;
CREATE TABLE public.icustays14 AS
SELECT ie.*, oa.oasis
FROM public.icustays13 AS ie
LEFT JOIN mimiciv_derived.oasis AS oa
ON ie.stay_id = oa.stay_id;

-- Add the SAPS II score
DROP TABLE IF EXISTS public.icustays15;
CREATE TABLE public.icustays15 AS
SELECT ie.*, sa.sapsii
FROM public.icustays14 AS ie
LEFT JOIN mimiciv_derived.sapsii AS sa
ON ie.stay_id = sa.stay_id;

-- Obtain the sofa score from first_day_sofa
DROP TABLE IF EXISTS public.icustays16;
CREATE TABLE public.icustays16 AS
SELECT ie.*, so.sofa
FROM public.icustays15 AS ie
LEFT JOIN mimiciv_derived.first_day_sofa AS so
ON ie.stay_id = so.stay_id;

---------------------------------------------------------------------------------------------------------
-- Add vital sign means and one worst extreme value
DROP TABLE IF EXISTS public.icustays17;
CREATE TABLE public.icustays17 AS
SELECT ie.*, 
    vs.heart_rate_mean, 
    vs.sbp_mean, 
    vs.dbp_mean, 
    vs.mbp_mean, 
    vs.resp_rate_mean, 
    vs.temperature_mean,
    vs.spo2_mean,
    vs.heart_rate_max, 
    vs.sbp_min, 
    vs.dbp_min, 
    vs.mbp_min, 
    vs.resp_rate_max, 
    vs.temperature_max,
    vs.spo2_min    
FROM public.icustays16 AS ie
LEFT JOIN mimiciv_derived.first_day_vitalsign AS vs
ON ie.stay_id = vs.stay_id;

-- Add the first vital sign measurements
DROP TABLE IF EXISTS public.icustays18;
CREATE TABLE public.icustays18 AS
WITH 
-- 1. Calculate the earliest non-null heart rate for each stay_id
first_hr AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.heart_rate AS heart_rate_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.heart_rate IS NOT NULL  -- keep only records with a value
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 2. Calculate the earliest non-null systolic blood pressure (sbp) for each stay_id
first_sbp AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.sbp AS sbp_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.sbp IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 3. Calculate the earliest non-null diastolic blood pressure (dbp) for each stay_id
first_dbp AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.dbp AS dbp_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.dbp IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 4. Calculate the earliest non-null mean arterial pressure (mbp) for each stay_id
first_mbp AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.mbp AS mbp_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.mbp IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 5. Calculate the earliest non-null respiratory rate (resp_rate) for each stay_id
first_rr AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.resp_rate AS resp_rate_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.resp_rate IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 6. Calculate the earliest non-null temperature for each stay_id
first_temp AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.temperature AS temperature_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.temperature IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
),
-- 7. Calculate the earliest non-null oxygen saturation (spo2) for each stay_id
first_spo2 AS (
    SELECT DISTINCT ON (vs.stay_id)
        vs.stay_id,
        vs.spo2 AS spo2_first
    FROM mimiciv_derived.vitalsign AS vs
    JOIN mimiciv_icu.icustays AS ie 
    ON vs.stay_id = ie.stay_id
    WHERE vs.spo2 IS NOT NULL
      AND vs.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                           AND ie.intime + INTERVAL '1 DAY'
    ORDER BY vs.stay_id, vs.charttime ASC
)
-- Main query: left join all separately calculated earliest vital sign values to the main table
SELECT 
    ie.*,
    fh.heart_rate_first,
    fs.sbp_first,
    fd.dbp_first,
    fm.mbp_first,
    fr.resp_rate_first,
    ft.temperature_first,
    fspo2.spo2_first
FROM public.icustays17 AS ie
-- Left join each earliest vital sign value one by one to ensure no main-table records are lost
LEFT JOIN first_hr   AS fh    ON ie.stay_id = fh.stay_id
LEFT JOIN first_sbp  AS fs    ON ie.stay_id = fs.stay_id
LEFT JOIN first_dbp  AS fd    ON ie.stay_id = fd.stay_id
LEFT JOIN first_mbp  AS fm    ON ie.stay_id = fm.stay_id
LEFT JOIN first_rr   AS fr    ON ie.stay_id = fr.stay_id
LEFT JOIN first_temp AS ft    ON ie.stay_id = ft.stay_id
LEFT JOIN first_spo2 AS fspo2 ON ie.stay_id = fspo2.stay_id;

-- Add urine output
DROP TABLE IF EXISTS public.icustays19;
CREATE TABLE public.icustays19 AS
SELECT ie.*, uo.urineoutput    
FROM public.icustays18 AS ie
LEFT JOIN mimiciv_derived.first_day_urine_output AS uo
ON ie.stay_id = uo.stay_id;

---------------------------------------------------------------------------------------------------------
-- Add laboratory results. First prepare the various laboratory result tables needed, then join them to the main table.
-- Based on the mimiciv_derived.complete_blood_count table, extract the aggregated values of the complete blood count on the first day of ICU admission (extracting only data not included in first_day_lab), named cbc_p1
DROP TABLE IF EXISTS public.cbc_p1;  
CREATE TABLE public.cbc_p1 AS
SELECT
  ie.subject_id,
  ie.stay_id,
  MIN(mch) AS mch_min,
  MAX(mch) AS mch_max,
  MIN(mchc) AS mchc_min,
  MAX(mchc) AS mchc_max,
  MIN(mcv) AS mcv_min,
  MAX(mcv) AS mcv_max,
  MIN(rbc) AS rbc_min,
  MAX(rbc) AS rbc_max,
  MIN(rdw) AS rdw_min,
  MAX(rdw) AS rdw_max,
  MIN(rdwsd) AS rdwsd_min,
  MAX(rdwsd) AS rdwsd_max
FROM mimiciv_icu.icustays AS ie
LEFT JOIN mimiciv_derived.complete_blood_count AS cbc
  ON ie.subject_id = cbc.subject_id
  AND cbc.charttime >= ie.intime - INTERVAL '6 HOUR'
  AND cbc.charttime <= ie.intime + INTERVAL '1 DAY'
GROUP BY
  ie.subject_id,
  ie.stay_id;

-- Based on the mimiciv_derived.complete_blood_count table, extract the first values of the complete blood count on the first day of ICU admission, generating the cbc_p2 table
DROP TABLE IF EXISTS public.cbc_p2;  
CREATE TABLE public.cbc_p2 AS
WITH cbc_time_filtered AS (
    -- Step 1: join the tables and filter the time window, keeping the base data
    SELECT 
        ie.stay_id,
        cbc.charttime,
        cbc.hematocrit,
        cbc.hemoglobin,
        cbc.mch,
        cbc.mchc,
        cbc.mcv,
        cbc.platelet,
        cbc.rbc,
        cbc.rdw,
        cbc.rdwsd,
        cbc.wbc
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.complete_blood_count AS cbc
        ON cbc.subject_id = ie.subject_id
        AND cbc.hadm_id = ie.hadm_id  -- additional join condition to avoid matching across admissions
        AND cbc.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
-- Extract the "first non-null value under stay_id" separately for each indicator
hct_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        hematocrit AS hematocrit_first
    FROM cbc_time_filtered
    WHERE hematocrit IS NOT NULL  -- filter NULL values
    ORDER BY stay_id, charttime ASC  -- in ascending time order, take the first record
),
hgb_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        hemoglobin AS hemoglobin_first
    FROM cbc_time_filtered
    WHERE hemoglobin IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
mch_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        mch AS mch_first
    FROM cbc_time_filtered
    WHERE mch IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
mchc_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        mchc AS mchc_first
    FROM cbc_time_filtered
    WHERE mchc IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
mcv_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        mcv AS mcv_first
    FROM cbc_time_filtered
    WHERE mcv IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
platelet_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        platelet AS platelet_first
    FROM cbc_time_filtered
    WHERE platelet IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
rbc_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        rbc AS rbc_first
    FROM cbc_time_filtered
    WHERE rbc IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
rdw_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        rdw AS rdw_first
    FROM cbc_time_filtered
    WHERE rdw IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
rdwsd_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        rdwsd AS rdwsd_first
    FROM cbc_time_filtered
    WHERE rdwsd IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
wbc_first AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        wbc AS wbc_first
    FROM cbc_time_filtered
    WHERE wbc IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
-- Finally join all indicators, ensuring every stay_id is retained (LEFT JOIN)
SELECT 
    ie.stay_id,
    hct.hematocrit_first,
    hgb.hemoglobin_first,
    mch.mch_first,
    mchc.mchc_first,
    mcv.mcv_first,
    plt.platelet_first,
    rbc.rbc_first,
    rdw.rdw_first,
    rdwsd.rdwsd_first,
    wbc.wbc_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN hct_first AS hct ON ie.stay_id = hct.stay_id
LEFT JOIN hgb_first AS hgb ON ie.stay_id = hgb.stay_id
LEFT JOIN mch_first AS mch ON ie.stay_id = mch.stay_id
LEFT JOIN mchc_first AS mchc ON ie.stay_id = mchc.stay_id
LEFT JOIN mcv_first AS mcv ON ie.stay_id = mcv.stay_id
LEFT JOIN platelet_first AS plt ON ie.stay_id = plt.stay_id
LEFT JOIN rbc_first AS rbc ON ie.stay_id = rbc.stay_id
LEFT JOIN rdw_first AS rdw ON ie.stay_id = rdw.stay_id
LEFT JOIN rdwsd_first AS rdwsd ON ie.stay_id = rdwsd.stay_id
LEFT JOIN wbc_first AS wbc ON ie.stay_id = wbc.stay_id;

-- Based on the mimiciv_derived.blood_differential table, extract the first values of the complete blood count on the first day of ICU admission, generating the cbc_p3 table
DROP TABLE IF EXISTS public.cbc_p3;  
CREATE TABLE public.cbc_p3 AS
WITH blood_differential_filtered AS (
    SELECT 
        ie.stay_id,
        bd.charttime,
        bd.wbc,
        bd.neutrophils,
        bd.lymphocytes
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.blood_differential AS bd
        ON bd.subject_id = ie.subject_id
        AND bd.hadm_id = ie.hadm_id
        AND bd.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_wbc AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        wbc AS wbc_first
    FROM blood_differential_filtered
    WHERE wbc IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_neutrophils AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        neutrophils AS neutrophils_first
    FROM blood_differential_filtered
    WHERE neutrophils IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_lymphocytes AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        lymphocytes AS lymphocytes_first
    FROM blood_differential_filtered
    WHERE lymphocytes IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_wbc.wbc_first,
    first_neutrophils.neutrophils_first,
    first_lymphocytes.lymphocytes_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_wbc ON ie.stay_id = first_wbc.stay_id
LEFT JOIN first_neutrophils ON ie.stay_id = first_neutrophils.stay_id
LEFT JOIN first_lymphocytes ON ie.stay_id = first_lymphocytes.stay_id;

-- Based on the chemistry table, extract the first values of the biochemistry data on the first day of ICU admission, generating the chemistry_first table
DROP TABLE IF EXISTS public.chemistry_first;  
CREATE TABLE public.chemistry_first AS
WITH chemistry_filtered AS (
    SELECT 
        ie.stay_id,
        ch.charttime,
        ch.albumin, ch.aniongap, ch.bicarbonate, ch.bun,
        ch.calcium, ch.chloride, ch.creatinine, ch.glucose,
        ch.sodium, ch.potassium
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.chemistry AS ch
        ON ch.subject_id = ie.subject_id
        AND ch.hadm_id = ie.hadm_id  -- additional join condition to avoid matching across admissions
        AND ch.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_albumin AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        albumin AS albumin_first
    FROM chemistry_filtered
    WHERE albumin IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_aniongap AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        aniongap AS aniongap_first
    FROM chemistry_filtered
    WHERE aniongap IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bicarbonate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bicarbonate AS bicarbonate_first
    FROM chemistry_filtered
    WHERE bicarbonate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bun AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bun AS bun_first
    FROM chemistry_filtered
    WHERE bun IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_calcium AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        calcium AS calcium_first
    FROM chemistry_filtered
    WHERE calcium IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_chloride AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        chloride AS chloride_first
    FROM chemistry_filtered
    WHERE chloride IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_creatinine AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        creatinine AS creatinine_first
    FROM chemistry_filtered
    WHERE creatinine IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_glucose AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        glucose AS glucose_first
    FROM chemistry_filtered
    WHERE glucose IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_sodium AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        sodium AS sodium_first
    FROM chemistry_filtered
    WHERE sodium IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_potassium AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        potassium AS potassium_first
    FROM chemistry_filtered
    WHERE potassium IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_albumin.albumin_first,
    first_aniongap.aniongap_first,
    first_bicarbonate.bicarbonate_first,
    first_bun.bun_first,
    first_calcium.calcium_first,
    first_chloride.chloride_first,
    first_creatinine.creatinine_first,
    first_glucose.glucose_first,
    first_sodium.sodium_first,
    first_potassium.potassium_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_albumin ON ie.stay_id = first_albumin.stay_id
LEFT JOIN first_aniongap ON ie.stay_id = first_aniongap.stay_id
LEFT JOIN first_bicarbonate ON ie.stay_id = first_bicarbonate.stay_id
LEFT JOIN first_bun ON ie.stay_id = first_bun.stay_id
LEFT JOIN first_calcium ON ie.stay_id = first_calcium.stay_id
LEFT JOIN first_chloride ON ie.stay_id = first_chloride.stay_id
LEFT JOIN first_creatinine ON ie.stay_id = first_creatinine.stay_id
LEFT JOIN first_glucose ON ie.stay_id = first_glucose.stay_id
LEFT JOIN first_sodium ON ie.stay_id = first_sodium.stay_id
LEFT JOIN first_potassium ON ie.stay_id = first_potassium.stay_id;

-- Based on the bg table, extract the first values of the blood gas data on the first day of ICU admission, generating the bg_first_art table (restricted to arterial blood)
SELECT DISTINCT specimen FROM mimiciv_derived.bg;
DROP TABLE IF EXISTS public.bg_first_art;  
CREATE TABLE public.bg_first_art AS
WITH bg_filtered AS (
    SELECT 
        ie.stay_id,
        bg.charttime,
        bg.baseexcess,
        bg.bicarbonate,
        bg.lactate,
        bg.pco2,
        bg.po2,
        bg.ph,
        bg.pao2fio2ratio
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.bg AS bg
        ON bg.subject_id = ie.subject_id
        AND bg.hadm_id = ie.hadm_id
        AND bg.specimen = 'ART.' -- restrict to arterial blood
        AND bg.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_baseexcess AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        baseexcess AS baseexcess_first
    FROM bg_filtered
    WHERE baseexcess IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bicarbonate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bicarbonate AS bicarbonate_first
    FROM bg_filtered
    WHERE bicarbonate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_lactate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        lactate AS lactate_first
    FROM bg_filtered
    WHERE lactate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_pco2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        pco2 AS pco2_first
    FROM bg_filtered
    WHERE pco2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_po2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        po2 AS po2_first
    FROM bg_filtered
    WHERE po2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ph AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ph AS ph_first
    FROM bg_filtered
    WHERE ph IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_pao2fio2ratio AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        pao2fio2ratio AS pao2fio2ratio_first
    FROM bg_filtered
    WHERE pao2fio2ratio IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_baseexcess.baseexcess_first,
    first_bicarbonate.bicarbonate_first,
    first_lactate.lactate_first,
    first_pco2.pco2_first,
    first_po2.po2_first,
    first_ph.ph_first,
    first_pao2fio2ratio.pao2fio2ratio_first    
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_baseexcess ON ie.stay_id = first_baseexcess.stay_id
LEFT JOIN first_bicarbonate ON ie.stay_id = first_bicarbonate.stay_id
LEFT JOIN first_lactate ON ie.stay_id = first_lactate.stay_id
LEFT JOIN first_pco2 ON ie.stay_id = first_pco2.stay_id
LEFT JOIN first_po2 ON ie.stay_id = first_po2.stay_id
LEFT JOIN first_ph ON ie.stay_id = first_ph.stay_id
LEFT JOIN first_pao2fio2ratio ON ie.stay_id = first_pao2fio2ratio.stay_id;

-- Based on the bg table, extract the first values of the blood gas data on the first day of ICU admission, generating the bg_first_artcv table (restricted to arterial or central venous blood)
SELECT DISTINCT specimen FROM mimiciv_derived.bg;
DROP TABLE IF EXISTS public.bg_first_artcv;  
CREATE TABLE public.bg_first_artcv AS
WITH bg_filtered AS (
    SELECT 
        ie.stay_id,
        bg.charttime,
        bg.baseexcess,
        bg.bicarbonate,
        bg.lactate,
        bg.pco2,
        bg.po2,
        bg.ph
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.bg AS bg
        ON bg.subject_id = ie.subject_id
        AND bg.hadm_id = ie.hadm_id
        AND bg.specimen IN ('ART.', 'CENTRAL VENOUS.') -- restrict to arterial or central venous blood
        AND bg.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_baseexcess AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        baseexcess AS baseexcess_first
    FROM bg_filtered
    WHERE baseexcess IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bicarbonate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bicarbonate AS bicarbonate_first
    FROM bg_filtered
    WHERE bicarbonate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_lactate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        lactate AS lactate_first
    FROM bg_filtered
    WHERE lactate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_pco2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        pco2 AS pco2_first
    FROM bg_filtered
    WHERE pco2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_po2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        po2 AS po2_first
    FROM bg_filtered
    WHERE po2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ph AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ph AS ph_first
    FROM bg_filtered
    WHERE ph IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_baseexcess.baseexcess_first,
    first_bicarbonate.bicarbonate_first,
    first_lactate.lactate_first,
    first_pco2.pco2_first,
    first_po2.po2_first,
    first_ph.ph_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_baseexcess ON ie.stay_id = first_baseexcess.stay_id
LEFT JOIN first_bicarbonate ON ie.stay_id = first_bicarbonate.stay_id
LEFT JOIN first_lactate ON ie.stay_id = first_lactate.stay_id
LEFT JOIN first_pco2 ON ie.stay_id = first_pco2.stay_id
LEFT JOIN first_po2 ON ie.stay_id = first_po2.stay_id
LEFT JOIN first_ph ON ie.stay_id = first_ph.stay_id;

-- Based on the bg table, extract the first values of the blood gas data on the first day of ICU admission, generating the bg_first table (without restricting the blood sampling site)
DROP TABLE IF EXISTS public.bg_first;  
CREATE TABLE public.bg_first AS
WITH bg_filtered AS (
    SELECT 
        ie.stay_id,
        bg.charttime,
        bg.baseexcess,
        bg.bicarbonate,
        bg.lactate,
        bg.pco2,
        bg.po2,
        bg.ph
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.bg AS bg
        ON bg.subject_id = ie.subject_id
        AND bg.hadm_id = ie.hadm_id
        AND bg.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_baseexcess AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        baseexcess AS baseexcess_first
    FROM bg_filtered
    WHERE baseexcess IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bicarbonate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bicarbonate AS bicarbonate_first
    FROM bg_filtered
    WHERE bicarbonate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_lactate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        lactate AS lactate_first
    FROM bg_filtered
    WHERE lactate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_pco2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        pco2 AS pco2_first
    FROM bg_filtered
    WHERE pco2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_po2 AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        po2 AS po2_first
    FROM bg_filtered
    WHERE po2 IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ph AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ph AS ph_first
    FROM bg_filtered
    WHERE ph IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_baseexcess.baseexcess_first,
    first_bicarbonate.bicarbonate_first,
    first_lactate.lactate_first,
    first_pco2.pco2_first,
    first_po2.po2_first,
    first_ph.ph_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_baseexcess ON ie.stay_id = first_baseexcess.stay_id
LEFT JOIN first_bicarbonate ON ie.stay_id = first_bicarbonate.stay_id
LEFT JOIN first_lactate ON ie.stay_id = first_lactate.stay_id
LEFT JOIN first_pco2 ON ie.stay_id = first_pco2.stay_id
LEFT JOIN first_po2 ON ie.stay_id = first_po2.stay_id
LEFT JOIN first_ph ON ie.stay_id = first_ph.stay_id;

-- Create the first_day_phosphate table
-- Find the test itemid corresponding to phosphate
SELECT * FROM mimiciv_hosp.d_labitems
WHERE LOWER(label) LIKE '%phosphate%'; --50970
-- Add phosphate. The reason the other parameters are aggregated with MAX grouped by le.specimen_id here is that, in principle, a single specimen should have only one result for a given test, but it is possible that because the first measurement was inaccurate, the remaining sample was used to run the test again, in which case taking the last measurement would be more accurate. However, the official MIMIC code does not take the last measurement; it takes the MAX instead, to simplify the code.
DROP TABLE IF EXISTS public.phosphate; 
CREATE TABLE public.phosphate AS
SELECT
  MAX(subject_id) AS subject_id,
  MAX(hadm_id) AS hadm_id,
  MAX(charttime) AS charttime,
  le.specimen_id, 
  MAX(valuenum) AS phosphate
FROM mimiciv_hosp.labevents AS le
WHERE
  le.itemid = 50970
  AND NOT valuenum IS NULL
  AND valuenum > 0
GROUP BY le.specimen_id;
-- Generate first_day_phosphate
DROP TABLE IF EXISTS public.first_day_phosphate;  
CREATE TABLE public.first_day_phosphate AS
WITH phosphate_filtered AS (
    SELECT 
        ie.stay_id,
        ph.charttime,
        ph.phosphate
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN public.phosphate AS ph
        ON ph.subject_id = ie.subject_id
        AND ph.hadm_id = ie.hadm_id
        AND ph.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_phosphate AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        phosphate AS phosphate_first
    FROM phosphate_filtered
    WHERE phosphate IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
minmax_phosphate AS (
    SELECT 
        stay_id,
        MIN(phosphate) AS phosphate_min,
        MAX(phosphate) AS phosphate_max
    FROM phosphate_filtered
    GROUP BY stay_id
)
SELECT 
    ie.stay_id,
    first_phosphate.phosphate_first,
    minmax_phosphate.phosphate_min,
    minmax_phosphate.phosphate_max
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_phosphate ON ie.stay_id = first_phosphate.stay_id
LEFT JOIN minmax_phosphate ON ie.stay_id = minmax_phosphate.stay_id;

-- Based on the enzyme table, extract the first values of the enzyme data on the first day of ICU admission, generating the enzyme_first table
DROP TABLE IF EXISTS public.enzyme_first;  
CREATE TABLE public.enzyme_first AS
WITH enzyme_filtered AS (
    SELECT 
        ie.stay_id,
        en.charttime,
        en.alt,
        en.alp,
        en.ast,
        en.bilirubin_total,
        en.ck_cpk AS ck,
        en.ck_mb,
        en.ggt,
        en.ld_ldh AS ldh
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.enzyme AS en
        ON en.subject_id = ie.subject_id
        AND en.hadm_id = ie.hadm_id
        AND en.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_alt AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        alt AS alt_first
    FROM enzyme_filtered
    WHERE alt IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_alp AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        alp AS alp_first
    FROM enzyme_filtered
    WHERE alp IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ast AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ast AS ast_first
    FROM enzyme_filtered
    WHERE ast IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_bilirubin_total AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        bilirubin_total AS bilirubin_total_first
    FROM enzyme_filtered
    WHERE bilirubin_total IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ck AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ck AS ck_first
    FROM enzyme_filtered
    WHERE ck IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ck_mb AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ck_mb AS ck_mb_first
    FROM enzyme_filtered
    WHERE ck_mb IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ggt AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ggt AS ggt_first
    FROM enzyme_filtered
    WHERE ggt IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ldh AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ldh AS ldh_first
    FROM enzyme_filtered
    WHERE ldh IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_alt.alt_first,
    first_alp.alp_first,
    first_ast.ast_first,
    first_bilirubin_total.bilirubin_total_first,
    first_ck.ck_first,
    first_ck_mb.ck_mb_first,
    first_ggt.ggt_first,
    first_ldh.ldh_first    
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_alt ON ie.stay_id = first_alt.stay_id
LEFT JOIN first_alp ON ie.stay_id = first_alp.stay_id
LEFT JOIN first_ast ON ie.stay_id = first_ast.stay_id
LEFT JOIN first_bilirubin_total ON ie.stay_id = first_bilirubin_total.stay_id
LEFT JOIN first_ck ON ie.stay_id = first_ck.stay_id
LEFT JOIN first_ck_mb ON ie.stay_id = first_ck_mb.stay_id
LEFT JOIN first_ggt ON ie.stay_id = first_ggt.stay_id
LEFT JOIN first_ldh ON ie.stay_id = first_ldh.stay_id;

-- Based on the coagulation table, extract the first values of the coagulation data on the first day of ICU admission, generating the coagulation_first table
DROP TABLE IF EXISTS public.coagulation_first;  
CREATE TABLE public.coagulation_first AS
WITH coagulation_filtered AS (
    SELECT 
        ie.stay_id,
        co.charttime,
        co.inr,
        co.pt,
        co.ptt
    FROM mimiciv_icu.icustays AS ie 
    LEFT JOIN mimiciv_derived.coagulation AS co
        ON co.subject_id = ie.subject_id
        AND co.hadm_id = ie.hadm_id
        AND co.charttime BETWEEN ie.intime - INTERVAL '6 HOUR' 
                              AND ie.intime + INTERVAL '1 DAY'
),
first_inr AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        inr AS inr_first
    FROM coagulation_filtered
    WHERE inr IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_pt AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        pt AS pt_first
    FROM coagulation_filtered
    WHERE pt IS NOT NULL
    ORDER BY stay_id, charttime ASC
),
first_ptt AS (
    SELECT DISTINCT ON (stay_id)
        stay_id,
        ptt AS ptt_first
    FROM coagulation_filtered
    WHERE ptt IS NOT NULL
    ORDER BY stay_id, charttime ASC
)
SELECT 
    ie.stay_id,
    first_inr.inr_first,
    first_pt.pt_first,
    first_ptt.ptt_first
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_inr ON ie.stay_id = first_inr.stay_id
LEFT JOIN first_pt ON ie.stay_id = first_pt.stay_id
LEFT JOIN first_ptt ON ie.stay_id = first_ptt.stay_id;

---------------------------------------------------------------------------------------------------------
-- Add laboratory items from the following tables:
--mimiciv_derived.first_day_lab  extreme values of complete blood count, biochemistry, coagulation, and enzymes
--mimiciv_derived.first_day_bg_art  bg first values   
--public.cbc_p1  complete blood count extreme values not covered by first_day_lab
--public.first_day_phosphate    phosphate extreme values and first values
--public.cbc_p2  complete blood count first values (excluding white blood cells)
--public.cbc_p3  first values of white blood cells, neutrophils, and lymphocytes in the complete blood count
--public.chemistry_first    biochemistry first values (fewer items)
--public.coagulation_first  coagulation first values
--public.enzyme_first   enzyme first values
--public.bg_first or bg_first_art or bg_first_artcv   bg first values


-- Add extreme values----------------------------------------------------------
-- Add laboratory extreme values from mimiciv_derived.first_day_lab
DROP TABLE IF EXISTS public.icustays20;
CREATE TABLE public.icustays20 AS
SELECT 
    ie.*, 
    l.albumin_min, l.alp_max, l.alt_max, l.aniongap_max, l.bun_max, 
    l.bicarbonate_min, l.calcium_min, l.chloride_max, l.creatinine_max, 
    l.glucose_max, l.hemoglobin_min, l.inr_max, l.ld_ldh_max AS ldh_max, 
    l.platelets_min, l.potassium_max, l.ptt_max, l.sodium_max, 
    l.bilirubin_total_max, l.wbc_max    
FROM public.icustays19 AS ie
LEFT JOIN mimiciv_derived.first_day_lab AS l
ON ie.stay_id = l.stay_id;

-- Add blood gas extreme values from first_day_bg (without restricting blood sampling site, excluding pco2 and po2)
DROP TABLE IF EXISTS public.icustays21;
CREATE TABLE public.icustays21 AS
SELECT 
    ie.*, 
    b.baseexcess_min, b.lactate_max, b.ph_min
FROM public.icustays20 AS ie
LEFT JOIN mimiciv_derived.first_day_bg AS b
ON ie.stay_id = b.stay_id;

-- Add blood gas extreme values from first_day_bg_art (including pco2 and po2)
DROP TABLE IF EXISTS public.icustays_s1;
CREATE TABLE public.icustays_s1 AS
SELECT 
    ie.*, 
    b.po2_min, pco2_max, pao2fio2ratio_min
FROM public.icustays21 AS ie
LEFT JOIN mimiciv_derived.first_day_bg_art AS b
ON ie.stay_id = b.stay_id;

-- Add other complete blood count extreme values from public.cbc_p1
DROP TABLE IF EXISTS public.icustays22;
CREATE TABLE public.icustays22 AS
SELECT 
    ie.*, 
    cbc.mchc_min, cbc.mcv_min, cbc.rdw_max
FROM public.icustays_s1 AS ie
LEFT JOIN public.cbc_p1 AS cbc
ON ie.stay_id = cbc.stay_id;

-- Add phosphate extreme values and first values from public.first_day_phosphate
DROP TABLE IF EXISTS public.icustays23;
CREATE TABLE public.icustays23 AS
SELECT 
    ie.*, 
    ph.phosphate_min,
    ph.phosphate_first
FROM public.icustays22 AS ie
LEFT JOIN public.first_day_phosphate AS ph
ON ie.stay_id = ph.stay_id;

-- Add first values----------------------------------------------------------
-- Add complete blood count first values from public.cbc_p2 and public.cbc_p3
DROP TABLE IF EXISTS public.icustays24;
CREATE TABLE public.icustays24 AS
SELECT 
    ie.*, 
    c.hematocrit_first, c.hemoglobin_first, c.mch_first, c.mchc_first, 
    c.mcv_first, c.platelet_first, c.rbc_first, c.rdw_first, c.wbc_first,
    cb.neutrophils_first, cb.lymphocytes_first
FROM public.icustays23 AS ie
LEFT JOIN public.cbc_p2 AS c ON ie.stay_id = c.stay_id
LEFT JOIN public.cbc_p3 AS cb ON ie.stay_id = cb.stay_id;

-- Add biochemistry first values from public.chemistry_first (fewer items)
-- Add coagulation first values from public.coagulation_first
-- Add enzyme first values from public.enzyme_first
DROP TABLE IF EXISTS public.icustays25;
CREATE TABLE public.icustays25 AS
SELECT 
    ie.*, 
    ch.albumin_first, ch.aniongap_first, ch.bicarbonate_first, 
    ch.bun_first, ch.calcium_first, ch.chloride_first, 
    ch.creatinine_first, ch.glucose_first, ch.sodium_first, ch.potassium_first,
    co.inr_first, co.pt_first, co.ptt_first, 
    en.alt_first, en.alp_first, en.ast_first, en.bilirubin_total_first, 
    en.ck_first, en.ck_mb_first, en.ggt_first, en.ldh_first
FROM public.icustays24 AS ie
LEFT JOIN public.chemistry_first   AS ch ON ie.stay_id = ch.stay_id
LEFT JOIN public.coagulation_first AS co ON ie.stay_id = co.stay_id
LEFT JOIN public.enzyme_first      AS en ON ie.stay_id = en.stay_id;

-- Add bg first values from public.bg_first (without restricting blood sampling site, excluding pco2 and po2)
DROP TABLE IF EXISTS public.icustays26;
CREATE TABLE public.icustays26 AS
SELECT 
    ie.*, 
    bg.baseexcess_first, bg.lactate_first, bg.ph_first
FROM public.icustays25 AS ie
LEFT JOIN public.bg_first AS bg ON ie.stay_id = bg.stay_id;

-- Add bg first values from public.bg_first_art (including pco2 and po2)
DROP TABLE IF EXISTS public.icustays_s2;
CREATE TABLE public.icustays_s2 AS
SELECT 
    ie.*, 
    bg.po2_first, bg.pco2_first, bg.pao2fio2ratio_first
FROM public.icustays26 AS ie
LEFT JOIN public.bg_first_art AS bg 
ON ie.stay_id = bg.stay_id;

----------------------------------
-- This section, based on the vasoactive_agent table in the mimiciv_derived module combined with the icustays table, extracts vasoactive drug use on the first day of ICU admission (binary), named the first_day_vasoactive table.
DROP TABLE IF EXISTS public.first_day_vasoactive;
CREATE TABLE public.first_day_vasoactive AS
WITH icu_info AS (
    SELECT 
        subject_id,
        stay_id,        
        intime - INTERVAL '6 HOUR' AS first_day_starttime,
        intime + INTERVAL '1 DAY' AS first_day_endtime
    FROM mimiciv_icu.icustays
),
first_day_vasoactive AS (
    SELECT 
        va.stay_id,
        MAX(CASE 
            WHEN va.starttime <= ie.first_day_endtime
            AND va.endtime >= ie.first_day_starttime
            AND COALESCE(dopamine, epinephrine, norepinephrine, phenylephrine, vasopressin, dobutamine, milrinone) IS NOT NULL
            THEN 1 
            ELSE 0 
        END) AS vasoactive
    FROM mimiciv_derived.vasoactive_agent AS va
    INNER JOIN icu_info AS ie
    ON va.stay_id = ie.stay_id
    GROUP BY va.stay_id
)
SELECT 
    ie.subject_id,
    ie.stay_id,
    COALESCE(va.vasoactive, 0) AS vasoactive
FROM mimiciv_icu.icustays AS ie
LEFT JOIN first_day_vasoactive AS va 
ON ie.stay_id = va.stay_id;

-- Add medication information
DROP TABLE IF EXISTS public.icustays27;
CREATE TABLE public.icustays27 AS
SELECT 
    ie.*, 
    va.vasoactive
FROM public.icustays_s2 AS ie
LEFT JOIN public.first_day_vasoactive AS va
ON ie.stay_id = va.stay_id;

-- This section, based on the ventilation table in the mimiciv_derived module combined with the icustays table, extracts mechanical ventilation use on the first day of ICU admission (binary), named the first_day_mechanical_ventilation table. Mechanical ventilation includes tracheostomy, invasive ventilation, and non-invasive ventilation.
DROP TABLE IF EXISTS public.first_day_mechanical_ventilation;
CREATE TABLE public.first_day_mechanical_ventilation AS
WITH temp1 AS(
    SELECT 
        vl.stay_id,
        MAX(CASE 
            WHEN vl.ventilation_status IN ('Tracheostomy', 'InvasiveVent', 'NonInvasiveVent')
            AND vl.starttime <= ie.intime + INTERVAL '1 DAY'
            AND vl.endtime >= ie.intime - INTERVAL '6 HOUR'
            THEN 1 
            ELSE 0 
        END) AS mechanical_ventilation
    FROM mimiciv_derived.ventilation AS vl
    INNER JOIN mimiciv_icu.icustays AS ie
    ON vl.stay_id = ie.stay_id
    GROUP BY vl.stay_id
)
SELECT 
    ie.subject_id,
    ie.stay_id,
    COALESCE(temp1.mechanical_ventilation, 0) AS mechanical_ventilation
FROM mimiciv_icu.icustays AS ie
LEFT JOIN temp1 ON ie.stay_id = temp1.stay_id;

-- Add mechanical ventilation information
DROP TABLE IF EXISTS public.icustays28;
CREATE TABLE public.icustays28 AS
SELECT 
    ie.*, 
    mv.mechanical_ventilation
FROM public.icustays27 AS ie
LEFT JOIN public.first_day_mechanical_ventilation AS mv
ON ie.stay_id = mv.stay_id;

-- Add echocardiographic LVEF; note that lvef here is text type and needs to be converted to numeric in R later
DROP TABLE IF EXISTS public.icustays29;
CREATE TABLE public.icustays29 AS
WITH lvef_closest AS (
    SELECT DISTINCT ON (ie.stay_id)
        ie.stay_id,
        lv.lvef,
        lv.measurement_datetime AS lvef_meas_time
    FROM public.icustays28 ie
    INNER JOIN public.lvef lv
        ON ie.subject_id = lv.subject_id
    WHERE
        lv.measurement_datetime BETWEEN 
            ie.intime - INTERVAL '6 hours' 
            AND ie.intime + INTERVAL '24 hours'
        AND lv.lvef IS NOT NULL
    ORDER BY
        ie.stay_id,
        -- Convert the time difference to seconds, take the absolute value; the smaller the value, the closer to intime
        ABS(EXTRACT(EPOCH FROM (lv.measurement_datetime - ie.intime))) ASC
)
SELECT
    ie.*,
    lc.lvef
FROM public.icustays28 ie
LEFT JOIN lvef_closest lc
    ON ie.stay_id = lc.stay_id;
    
-- Add NT-proBNP 50963
DROP TABLE IF EXISTS public.icustays30;
CREATE TABLE public.icustays30 AS
SELECT DISTINCT ON (ie.stay_id)
    ie.*,
    le.valuenum AS ntprobnp
FROM public.icustays29 AS ie
LEFT JOIN mimiciv_hosp.labevents AS le
    ON ie.subject_id = le.subject_id
    AND le.itemid = 50963
    AND le.charttime 
        BETWEEN ie.intime - INTERVAL '6 hours'
            AND ie.intime + INTERVAL '24 hours'
    AND le.valuenum IS NOT NULL
ORDER BY ie.stay_id, le.charttime ASC;
